### ISSUE TITLE
ModuleNotFoundError: No module named 'gcn_module'

### ISSUE THREAD

**Issue by Certainguys** [0shelter0/PDGCN#1]
亲爱的作者您好，非常幸运能参考您的代码，但在from gcn_module import *这行代码运行时报错“ModuleNotFoundError: No module named 'gcn_module'”，提示没有gcn模型，我查找了代码，只在ARG文件中找到了gcn模型，但是stage1阶段并没有调用ARG文件，所以很好奇这个gcn模型是怎么导入的，希望能得到您的回答

**Comment by JIANG-KING** [comment]
我也碰到了这个问题。请问你是怎么解决这个问题的

**Comment by Certainguys** [comment]
抱歉我很久不看gmail了，这个问题可以去这个网站上
https://github.com/JacobYuan7/DIN-Group-Activity-Recognition-Benchmark
使用其中的gcnmodule文件

祝顺利
JIANG-KING ***@***.***> 于2024年4月18日周四 16:37写道：
